version: '3.8'

services:
  postgresdb:
    build:
      context: ./postgresdb
    healthcheck:
      test: test -f /tmp/finished.ok
      interval: 5s
      timeout: 10s
      retries: 120
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_NAME_API=productapi

    ports:
      - '54321:5432'
    volumes:
      - postgres-data:/var/lib/postgresql

volumes:
  postgres-data: