version: "3.8"

services:
  elasticsearch:
    image: "docker.io/bitnami/elasticsearch:8.5.3"
    container_name: elasticsearch
    healthcheck:
      test: curl -s http://elasticsearch:9200 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 50    
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - elk      

  kibana:
    image: "docker.io/bitnami/kibana:8.5.3"
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS:http://elasticsearch:9200
    networks:
      - elk      
    depends_on:
      - elasticsearch

  logstash:
    build:
      context: logstash/
      dockerfile: Dockerfile

    ports:
      - 5044:5044
      - 5000:5000
      - 9600:9600
#    volumes:
#      - ./logstash/configs/:/usr/share/logstash/config:ro
#      - ./logstash/configs/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
#      - ./logstash/pipelines:/usr/share/logstash/config/pipelines:ro      
    environment:
      LS_JAVA_OPTS: -Xms512m -Xmx512m
#      LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
    networks:
      - elk
    depends_on:
      elasticsearch:
        condition: service_healthy  
  filebeatjson:
#    build:
#      context: ./filebeatjson
    image: elastic/filebeat:8.5.3      
    entrypoint: "filebeat -e -strict.perms=false"
    container_name: filebeatjson
    volumes:
      - ./filebeatjson/filebeat.yml :/usr/share/filebeat/filebeat.yml:ro
      - ./logs:/src/logs
    networks:
      - elk      
    depends_on:
      elasticsearch:
        condition: service_healthy      
      logstash:
        condition: service_started

networks:
  elk:
    driver: bridge
          
volumes:
  elasticsearch_data:
    driver: local
  logstash_data:
    driver: local
  postgres-data:
    driver: local