version: "3.8"

services:
  elasticsearch:
    image: "docker.io/bitnami/elasticsearch:8"
    container_name: elasticsearch
    environment:
      #- "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
volumes:
  elasticsearch_data:
    driver: local