version: "3.5"
networks:
  test:
services:
  fluentd:
    container_name: fluentd
    image: fluent/fluentd:latest
    environment:
      - POSTGRES_USER=test.conf      
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      # добавляем конфигурацию в контейнер
      - ./fluentd.config:/fluentd/etc/test.conf 
    networks:
      - test        
  ubuntu:
    image: ubuntu
    command: [/bin/echo, "Kevcodez"]
    restart: unless-stopped
    depends_on:
      - fluentd
    logging:
      driver: fluentd
      options:
        tag: docker-ubuntu
        address: "fluentd:24224"
    networks:
      - test        